version: '3'
services:
  nginx-nsalinas:
    build: 
      context: ./nginx
      dockerfile: dockerfile.local
    links:
      - app-nsalinas
    ports:
    - "3000:80"

  app-nsalinas:
    build: ./app
    expose:
      - "3001"
    environment:
      - NAME=nsalinas